version : '3'
services:
  db:
    image: influxdb
    container_name: influxdb
    volumes:
      - ~/influxDB:/var/lib/influxdb
    ports: 
      - 8086:8086

  collector:
    image: collector
    container_name: collector
    build:
      context: ./microDB_store
      dockerfile: Dockerfile
                
  microapi_bme280: 
    image: microapi_bme280
    container_name: bme280_api
    privileged: true
    ports:
      - 5000:5000

  dashboard:
    image: grafana/grafana-arm32v7-linux:dev-musl
    container_name: grafana 
    environment: 
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
    volumes:
      - ~/grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000

  camera:
    image: picam
    container_name: picam
    devices:
      - /dev/video0:/dev/video0
    ports:
      - 8081:8081

  microapi_lightsensor:
    image: microapi_lightsensor
    container_name: lightsensor_api
    privileged: true
    ports:
      - 5001:5001