version : '3'
services:
  db:
    image: influxdb
    name: influxdb
    volumes:
    - ~/influxDB:/var/lib/influxdb
    ports: 
    - 8086:8086

  collector:
    image: collector
    name: collector
                
  microapi_bme280: 
    image: microapi_bme280
    name: bme280_api
    privileged: true
    ports:
    - 5000:5000

  dashboard:
    image: grafana/grafana-arm32v7-linux:dev-musl
    name: grafana 
    environment: 
     - GF_PANELS_DISABLE_SANITIZE_HTML=true
    volumes:
    - ~/grafana-storage:/var/lib/grafana
    ports:
    - 3000:3000

  # camera:
  #   image: grafana/grafana-arm32v7-linux:dev-musl 
  #   environment: 
  #    - GF_PANELS_DISABLE_SANITIZE_HTML=true
  #   volumes:
  #   - ~/grafana-storage:/var/lib/grafana
  #   ports:
  #   - 3000:3000